# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeAccount')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeAccount'),
        ),
    ]
